name: Milestone Tracking

on:
  issues:
    types:
      - closed
  milestone:
    types:
      - opened
      - edited
      - deleted

jobs:
  track_milestones:
    runs-on: ubuntu-latest

    steps:
      - name: Check Milestones
        run: |
          # Your custom script or command to check and update milestones here
          
          # For example, you can use the GitHub API to fetch and update milestones.
          # In this example, we'll simply echo a message as the "output."

          echo "Milestone tracking script executed successfully."

      - name: Set Output
        id: output
        run: echo "Milestone tracking completed."

      - name: Display Output
        run: |
          echo "The milestone tracking workflow produced the following output:"
          echo "${{ steps.output.outputs.output_message }}"
